name: Terraform Deploy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.0

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        run: terraform init -backend-config=backend.conf
        env:
            ARM_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
            ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
            ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        env:
            ARM_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
            ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
            ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
            TF_VAR_azure_client_id: ${{ vars.AZURE_CLIENT_ID }}
            TF_VAR_azure_subscription_id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
            TF_VAR_azure_tenant_id: ${{ vars.AZURE_TENANT_ID }}

      - name: Manual Approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: dppick2solutions
          minimum-approvals: 1

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        env:
            ARM_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
            ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
            ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
            TF_VAR_azure_client_id: ${{ vars.AZURE_CLIENT_ID }}
            TF_VAR_azure_subscription_id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
            TF_VAR_azure_tenant_id: ${{ vars.AZURE_TENANT_ID }}